language: shell
arch:
- arm64
os: linux
dist: bionic
services:
- docker
addons:
  apt:
    packages:
    - lshw
script:
- cat /proc/cpuinfo
- sudo lshw
- docker build -t rfinnie/finnixbuild:latest .
- docker run --rm --privileged rfinnie/finnixbuild:latest
